title: PlayYouQuiz Docs
description: All the PlayYouQuiz documentation!
theme: just-the-docs

url: https://playyouquiz.github.io

aux_links:
  Template Repository: https://github.com/playyouquiz/docs
